config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments
  end
  root 'posts#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post
  before_action :find_comment, except: [:create]

  def create
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end

  def find_comment
    @comment = @post.comments.find(params[:id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_post_by_id, only: %i[show edit update destroy]

  def index
    @posts = Post.all.order('created_at DESC')
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description)
  end

  def find_post_by_id
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
	<p class="comment-content"><%= comment.content %></p>
	<p class="comment-posted-by">By <%= comment.user.email %> <%= time_ago_in_words(comment.created_at) %> ago</p>

	<div class="links">
			<% if user_signed_in? %>
				<% if comment.user_id == current_user.id %>
					<%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
					<%= link_to "Delete", post_comment_path(comment.post, comment), method: :delete, data: { confirm: "Are you sure?" } %>
				<% end %>
			<% end %>
	</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for ([@post, @post.comments.build]) do |f| %>
  <%= f.input :content, label: "Comment" %>
  <%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>
<%= simple_form_for ([@post, @comment]) do |f| %>
  <%= f.input :content, label: "Comments" %>
  <%= f.button :submit, :class => 'btn-custom' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sport Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Sport Forum", root_path, class: "navbar-brand" %>
        </div>

        <ul class="navbar-nav nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>

        <% if user_signed_in? %>
          <p><%= link_to "Post It", new_post_path, class: "navbar-text navbar-link" %></p>
        <% end %>

      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1 class="new-msg-header">Edit Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post|%>
  <div class="col-md-10 col-md-offset-1">
    <div class="message">
      <h2 class="message-title"><%= post.title %></h2>
      <%= link_to "Join Conversation", post, class: "btn-custom" %>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1 class="new-msg-header">New Post</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="message-show">
    <h2><%= @post.title %></h2>
    <p class="message-posted-by"><%= time_ago_in_words(@post.created_at) %> ago</p>
    <p class="message-desc"><%= @post.description %></p>

    <% if @post.comments.exists? %>
      <h3 class="comment-section-header">Comments:</h3>
      <p><%= render @post.comments %></p>
    <% end %>

    <% if user_signed_in? %>
      <h3 class="reply-to-msg">Join Discussion:</h3>
      <%= render 'comments/form' %>
    <% end %>

    <div class="links btn-group">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
      <% if user_signed_in? %>
				<% if @post.user_id == current_user.id %>
					<%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary" %>
          <%= link_to "Delete", post_path(@post), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?" } %>
				<% end %>
			<% end %>
    </div>
  </div>
</div>